### ISSUE TITLE
Error de conexion

### ISSUE THREAD

**Issue by guzman23** [bitrvmpd/Pebble-W10M#1]
Hola,

Acabo de adquirir un Pebble time y tengo un lumia 640 y me pasa lo siguiente:
- Cuando intento sincronizarlos, pebble no se queda permanentemente conectado al 640, se queda 2-3 seg y se desconecta.
- Si instalo el Pebble watch pro, solo se sincronizan cuando arranco la app. Si el 640 se bloquea o salgo de la app, automaticamente se desincronizan y pebble me avisa de que no esta conectado.
- Puse el movil en modo programador y me baje la app beta tester llamada Pebble Connect, la que te permite recibir notificaciones. Pues cuando la arranco, veo que detecta el pebble pero al segundo pierde conexion y me dice que hay un error.
- Estoy intentando instalar la tuya, pero creo que tengo que subir el lumia a W10, no? o funcionaria con W8.1?

Estoy intentando no devolverlo, porque crei que podria rcibir llamadas y notificaciones desde el 640, pero me he metido un buen chafon...

Gracias

**Comment by bitrvmpd** [comment]
Pues de partida deberias haber buscado que Pebble no tiene soporte oficial para windows phone, por lo tanto no está asegurado que funcione como debería.

No poseo un pebble time, para poder realizar pruebas.

Si, mi app que es alpha y sigue en desarrollo es para windows 10 y para instalarla necesitas bajar el sdk de win10. Pero como dije en el párrafo anterior no poseo un pebble time, sino el original.

Muchas funcionalidades del pebble time no funcionarán, como el reconocimiento de voz, el timeline y el control de música.

Saludos.
